spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cdb-7yjkkc7a.sql.tencentcdb.com:62332/db_warn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: myy
    password: myyun@r@myy
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 8
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      filters: stat,wall,log4j
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
 
eureka:                                 #注册服务
  client:
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/

server:
  port: 9081

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
          timeoutInMilliseconds: 30000
 
  ## Redis 配置
  ## Redis数据库索引（默认为0）
spring.redis.database: 0
  ## Redis服务器地址
spring.redis.host: 127.0.0.1
  ## Redis服务器连接端口
spring.redis.port: 6379
  ## Redis服务器连接密码（默认为空）
  #spring.redis.password=123456
  ## 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active: 8
  ## 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait: -1
  ## 连接池中的最大空闲连接
  #spring.redis.jedis.pool.max-idle=8
  ## 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle: 0
  ## 连接超时时间（毫秒）
spring.redis.timeout: 5000
