spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cdb-7yjkkc7a.sql.tencentcdb.com:62332/db_warn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: myy
    password: myyun@r@myy
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 8
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      filters: stat,wall,log4j
  jpa:
    database: mysql
    #show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
 
eureka:                                 #注册服务
  client:
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/

server:
  port: 8033

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
hystrix:
  threadpool:
    # default: 默认参数，作用的所有的hystrix的客户端,如果需要对某个具体的接口，可以写接口+方法名称
    default:
      coreSize: 500
  command:
    default:
#      circuitBreaker:
#        sleepWindowInMilliseconds: 1000
      execution:
        fallback:
          # 是否开启回退方法
          enabled: true
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#            strategy: SEMAPHORE  

feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: true
  okhttp:
    enabled: false
    
logging.level.com.moyuaninfo.cloud.client.CameraClient: debug
logging.level.com.moyuaninfo.cloud.client.DangerClient: debug
logging.level.com.moyuaninfo.cloud.client.LaboratoryClient: debug
logging.level.com.moyuaninfo.cloud.client.LiveBroClient: debug
logging.level.com.moyuaninfo.cloud.client.NewsConfigureClient: debug
logging.level.com.moyuaninfo.cloud.client.NewsPushClient: debug
logging.level.com.moyuaninfo.cloud.client.NoticeClient: debug
logging.level.com.moyuaninfo.cloud.client.PersonClient: debug
       
